// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) {
  return User(
    id: json['id'] as int ?? 0,
    userId: json['userId'] as int ?? 0,
    nickname: json['nickname'] as String ?? '',
    name: json['name'] as String ?? '',
    kind: json['kind'] as int ?? 2,
    avatar: json['avatar'] as String ?? '',
    avatarKey: json['avatarKey'] as String ?? '',
    gender: json['gender'] as int ?? 0,
    position: json['position'] as String ?? '',
    followNumber: json['followNumber'] as int ?? 0,
    fanNumber: json['fanNumber'] as int ?? 0,
    feedNumber: json['feedNumber'] as int ?? 0,
    birthday: json['birthday'] as String ?? '',
    city: json['city'] as String ?? '',
    cityName: json['cityName'] as String ?? '',
    signature: json['signature'] as String ?? '',
    company: json['company'] as String ?? '',
    companyAddress: json['companyAddress'] as String ?? '',
    unreadNumber: json['unreadNumber'] as int ?? 0,
    mobile: json['mobile'] as String ?? '',
    a2b: json['a2b'] as bool ?? false,
    b2a: json['b2a'] as bool ?? false,
    isMySelf: json['isMySelf'] as bool ?? false,
    isNew: json['isNew'] as bool ?? false,
    encryptedMobile: json['encryptedMobile'] as String ?? '',
    prompt: json['prompt'] as String ?? '',
    canEditName: json['canEditName'] as bool ?? false,
    info: (json['info'] as List)?.map((e) => e as String)?.toList() ?? [],
    isBindApple: json['isBindApple'] as bool ?? false,
    isBindWechat: json['isBindWechat'] as bool ?? false,
    isMaster: json['isMaster'] as bool ?? false,
    hasMP: json['hasMP'] as bool ?? false,
    supplierName: json['supplierName'] as String ?? '',
    vipKind: json['vipKind'] as int ?? 0,
    vipIcon: json['vipIcon'] as String ?? '',
    newProjectNum: json['newProjectNum'] as int ?? 0,
    jurisdiction: json['jurisdiction'] as String ?? '',
    auditStatus: json['auditStatus'] as int ?? 0,
    courseLikeNumber: json['courseLikeNumber'] as int ?? 0,
    newsLikeNumber: json['newsLikeNumber'] as int ?? 0,
    feedLikeNumber: json['feedLikeNumber'] as int ?? 0,
    projectLikeNumber: json['projectLikeNumber'] as int ?? 0,
  )
    ..projectNumber = json['projectNumber'] as int ?? 0
    ..shareUrl = json['shareUrl'] as String ?? ''
    ..passwordStatus = json['passwordStatus'] as bool ?? false
    ..isProfession = json['isProfession'] as bool ?? false
    ..isRealName = json['isRealName'] as bool ?? false;
}

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'id': instance.id,
      'userId': instance.userId,
      'nickname': instance.nickname,
      'name': instance.name,
      'kind': instance.kind,
      'avatar': instance.avatar,
      'avatarKey': instance.avatarKey,
      'gender': instance.gender,
      'position': instance.position,
      'followNumber': instance.followNumber,
      'fanNumber': instance.fanNumber,
      'feedNumber': instance.feedNumber,
      'projectLikeNumber': instance.projectLikeNumber,
      'feedLikeNumber': instance.feedLikeNumber,
      'courseLikeNumber': instance.courseLikeNumber,
      'newsLikeNumber': instance.newsLikeNumber,
      'projectNumber': instance.projectNumber,
      'birthday': instance.birthday,
      'city': instance.city,
      'cityName': instance.cityName,
      'signature': instance.signature,
      'company': instance.company,
      'companyAddress': instance.companyAddress,
      'unreadNumber': instance.unreadNumber,
      'mobile': instance.mobile,
      'a2b': instance.a2b,
      'b2a': instance.b2a,
      'isMySelf': instance.isMySelf,
      'isNew': instance.isNew,
      'encryptedMobile': instance.encryptedMobile,
      'prompt': instance.prompt,
      'canEditName': instance.canEditName,
      'shareUrl': instance.shareUrl,
      'passwordStatus': instance.passwordStatus,
      'info': instance.info,
      'isProfession': instance.isProfession,
      'isRealName': instance.isRealName,
      'isBindApple': instance.isBindApple,
      'isBindWechat': instance.isBindWechat,
      'isMaster': instance.isMaster,
      'hasMP': instance.hasMP,
      'supplierName': instance.supplierName,
      'vipKind': instance.vipKind,
      'vipIcon': instance.vipIcon,
      'newProjectNum': instance.newProjectNum,
      'jurisdiction': instance.jurisdiction,
      'auditStatus': instance.auditStatus,
    };
